### ISSUE TITLE
schema.sql Initialization Error: SELECT Statement Before Table Creation

### ISSUE THREAD

**Issue by hakong** [karih/fbsr_pontun#12]
Hello Team,

While setting up the database using the provided `schema.sql` file, I encountered an error related to the execution order of SQL statements. The `SELECT` statement that references the `shipment_items` table is placed before the table's creation, causing an initialization error in PostgreSQL.

**Error**:
```
psql:/docker-entrypoint-initdb.d/schema.sql:62: ERROR: relation "shipment_items" does not exist
LINE 2: FROM shipment_items si
^
```

**Proposed Solution**:
1. Move the `SELECT` statement (and any other queries relying on not-yet-created tables) to the bottom of the `schema.sql` file or after all the tables it references have been defined.
2. Ensure that the order of table creation respects the dependencies between tables.

Thank you!

**Comment by karih** [comment]
Resolved by https://github.com/karih/fbsr_pontun/commit/e21d55eea7f2043e553017c3f949fc897d7d5442 .
